env:
    MANIFEST: git://github.com/PitchBlackRecoveryProject/manifest_pb -b android-11.0
    DT_LINK: https://github.com/Atharv2951-Roms/device_samsung_j7velte
    DEVICE: j7velte
    OEM: samsung
    DT_PATH: device/$OEM/$DEVICE
    TARGET: recoveryimage
    EXTRA_CMD: git clone https://github.com/Atharv2951-Roms/ofrp_avtar misc
    OUTPUT: P*.zip 

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ubuntu:20.04
      cpu: 8
      memory: 32G
  
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - df -h
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio ccache neofetch -y
       - sudo apt install python2 -y
       - sudo ln -sf /usr/bin/python2 /usr/bin/python
       - git config --global user.name "Atharv2951"
       - git config --global user.email "atharv2951@gmail.com"
       - git clone https://github.com/akhilnarang/scripts.git ~/scripts
       - cd ~/scripts
       - sudo bash setup/android_build_env.sh
       - cd ~
  
  Neofetch_script:
       - neofetch
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - repo init --depth=1 -u $MANIFEST 
      - repo sync -j16 --force-sync --no-tags --no-clone-bundle
      - git clone $DT_LINK $DT_PATH
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"
  
  fox-10-setup_script:
      - cd ~/work
      - cd build
      
  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export LC_ALL="C"
      - export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - . build/envsetup.sh
      - . $DT_PATH/vendorsetup.sh
      - lunch omni_$DEVICE-eng
      - mka recoveryimage
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
        

