env:
    MANIFEST: https://github.com/PixelExperience/manifest.git -b eleven-plus
    DEVICE: A6020
    OEM: lenovo
    DT_LINK: https://github.com/ibratabian17/device_lenovo_A6020.git
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/hsj51/vendor_lenovo_A6020.git
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/hsj51/kernel_lenovo_msm8916.git
    PLATFORM: msm8916
    KT_PATH: kernel/$OEM/$PLATFORM
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: aosp_"$DEVICE"-userdebug

task:
  name: "Building..."
  timeout_in: 240m  
  container:
      image: ubuntu:20.04
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio ccache clang -y
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "Sushrut1101"
       - git config --global user.email "guptasushrut@gmail.com"
       - git clone https://github.com/akhilnarang/scripts.git ~/scripts
       - cd ~/scripts
       - sudo bash setup/android_build_env.sh
       - cd ~
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - repo init -u $MANIFEST
      - repo sync -j31 --force-sync --no-tags --no-clone-bundle
      - git clone $DT_LINK $DT_PATH
      - git clone $VT_LINK $VT_PATH
      - git clone $KT_LINK $KT_PATH
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - . build/envsetup.sh
      - lunch "$LUNCH_COMBO"
      - mka -j31 $TARGET
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file *.zip https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
        

